---
title: "Staff Absences"
author: "Fiona Spooner"
date: "03/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Libraries
```{r}
library(readxl)
library(data.table)
library(dplyr)
library(ggplot2)
library(janitor)
library(tidyr)
```

```{r}
hosp <- "NDDH" #Name of hospital for plot labels

in_file <- "Staff_Absences_NDDH_20200406.xlsx" #excel file with data

end_date <- as.Date("2020-04-16")  #End date for projections

in_dir <- "C:/Users/Fiona/University of Exeter/COVID19 Modelling - Documents/Staff_Absences/Data_from_Claire/"

scen_data <- "Devon_projection.RData" #scenario rates
load(paste0(in_dir,scen_data))
scen_in <- Devon_projection

out_dir <- paste0("C:/Users/Fiona/University of Exeter/COVID19 Modelling - Documents/Staff_Absences/Reports_and_Results/Outputs_",format(Sys.Date(), "%Y%m%d"), "/") 

```

Loading Data
```{r}
Daily_Absences_All_Staff <-
  read_excel(paste0(
    in_dir,
    in_file
  ),
    "Daily_Absences_All_Staff",
    col_names = TRUE
  ) %>% 
  mutate(Staff_Absences_Perc = Staff_Absences_Perc/100, 
         Staff_Absences_Covid_Perc = Staff_Absences_Covid_Perc/100)

Daily_Absences_All_Staff$Staff_Absences_NoCovid_Perc = Daily_Absences_All_Staff$Staff_Absences_Perc -
  Daily_Absences_All_Staff$Staff_Absences_Covid_Perc

first_date <- as.Date(max(Daily_Absences_All_Staff$Date))


```

Scenario Scaling Function
```{r}
scenario_scaler <- function(scenario_name, name_out,real_data, start_date_model, end_date_model){
  
  scen <- scen_in %>% 
    select(date, {{scenario_name}}) %>% 
    filter(date >= {{start_date_model}} & date <= {{end_date_model}}) %>% 
    mutate(scen_lag = c(NA, head({{scenario_name}},-1)))
  
  scen$scen_lag[1] <- scen$scen_lag[2]
  
  scen <- scen %>% 
    mutate(scen_pcnt = {{scenario_name}}/scen_lag, 
           scen_rt = cumprod(scen_pcnt),
           scen_model_pred = tail(real_data,1) * scen_rt) 
  
  df_out <- data.frame(dates_out = seq(start_date_model - (length(real_data)-1), end_date_model, by = "day"),
                       pred_out = c(head(real_data,-1), scen$scen_model_pred),
                       model_name = name_out)
  return(df_out)  
  
}

```

Scaling scenarios
```{r}
dev2_5 <- scenario_scaler(scenario_name = Rob2_5,
                name_out = "Dev2.5",
                real_data = Daily_Absences_All_Staff$Staff_Absences_Covid_Perc,
                start_date_model = first_date, 
                end_date_model = end_date)

dev50 <- scenario_scaler(scenario_name = Rob50,
                name_out = "Dev50",
                real_data = Daily_Absences_All_Staff$Staff_Absences_Covid_Perc,
                start_date_model = first_date, 
                end_date_model = end_date)

dev97_5 <- scenario_scaler(scenario_name = Rob97_5,
                name_out = "Dev97.5",
                real_data = Daily_Absences_All_Staff$Staff_Absences_Covid_Perc,
                start_date_model = first_date, 
                end_date_model = end_date)

nat75 <- scenario_scaler(scenario_name = Rt75,
                name_out = "Nat75",
                real_data = Daily_Absences_All_Staff$Staff_Absences_Covid_Perc,
                start_date_model = first_date, 
                end_date_model = end_date)

cov_long <- rbind(dev2_5, dev50, dev97_5, nat75)
colnames(cov_long) <- c("date", "value", "name")

```


```{r}

ggplot(cov_long %>% filter(date > as.Date("2020-03-19")), aes(x = date, y = value, group = name, col = name))+
  geom_line(aes(linetype = name, color = name, size = name))+
  geom_point(data = cov_long %>% filter(date <= first_date & date > as.Date("2020-03-19")),col = "black")+
  ggtitle(paste0("Rt for ", hosp))+
  scale_linetype_manual(values = c("twodash", "solid", "dotted", "solid") )+
  scale_color_manual(values = c(rep("#F8766D", 3), "#00BFC4"))+
  scale_size_manual(values = c(1,1.5,1,1.5))
  

```

No Cov Absences
```{r}
daily_abs_dates <-
  seq(min(as.Date(Daily_Absences_All_Staff$Date)), max(cov_long$date), by = "day")

daily_abs <-
  c(
    Daily_Absences_All_Staff$Staff_Absences_NoCovid_Perc,
    rep(
      tail(Daily_Absences_All_Staff$Staff_Absences_NoCovid_Perc, 1),
      length(daily_abs_dates) - length(Daily_Absences_All_Staff$Staff_Absences_NoCovid_Perc)
    )
  )

no_cov_abs <-
  data.frame(date = daily_abs_dates, no_cov_abs = daily_abs)

no_cov_abs <- no_cov_abs %>% 
  filter(date >= min(cov_df$date))
```

Staff Group Data
```{r}

Number_Staff_By_Group <- read_excel(paste0(in_dir,in_file), "Number_Staff_By_Group", col_names = TRUE) %>% 
  select(Group, FTE, Number_Staff) %>% 
  filter(!Group %in% c("Students", "Total"))

Number_Staff_By_Group$FTE <- as.numeric(Number_Staff_By_Group$FTE)

Number_Staff_By_Group$Number_Staff <- as.numeric(Number_Staff_By_Group$Number_Staff)

staff_num <- sum(Number_Staff_By_Group$Number_Staff)
group_max <- max(Number_Staff_By_Group$Number_Staff)

```

Group Weights

```{r}
Absences_By_Group <- read_excel(paste0(in_dir,in_file), "Absences_By_Group",col_names = TRUE) %>% 
  filter(!Group %in% c("Total", "Students")) %>% 
  left_join(., Number_Staff_By_Group, by = "Group") %>% 
  mutate(Staff_Absences_Perc = as.numeric(Staff_Absences_Perc)/100,
         Staff_Absences_Covid_Perc = as.numeric(Staff_Absences_Covid_Perc)/100) %>% 
  drop_na()


Absences_By_Group$Num_Absent <- Absences_By_Group$Staff_Absences_Covid_Perc *Absences_By_Group$Number_Staff

Absences_By_Group$Weights_Covid_Absences_By_Group <- Absences_By_Group$Num_Absent/sum(Absences_By_Group$Num_Absent)


staff_weights <- left_join(Number_Staff_By_Group, Absences_By_Group) %>% 
  select(Group, Number_Staff,Staff_Absences_Covid_Perc,Weights_Covid_Absences_By_Group) %>% 
  filter(!Group %in% c("Students", "Total"))
```

```{r}

combs <-
  expand.grid(group = unique(staff_weights$Group),
              model = unique(cov_long$name))

group_df <- data.frame()
for (i in 1:nrow(combs)) {
  group = combs$group[i]
  model = combs$model[i]
  
  staff_group <- staff_weights %>%
    filter(Group == group)
  
  cov_rates <- cov_long %>%
    filter(name == model)
  
  cov_staff_out <-
    sum(staff_weights$Number_Staff) * staff_group$Weights_Covid_Absences_By_Group * cov_rates$value
  no_cov_staff_out <-
    sum(staff_weights$Number_Staff) * staff_group$Weights_Covid_Absences_By_Group * no_cov_abs$no_cov_abs
  total_staff_out <- cov_staff_out + no_cov_staff_out
  
  num_staff <-  staff_group$Number_Staff
  group_out <- data.frame(
    date = cov_df$date,
    group = group,
    model = model,
    cov_staff_out = cov_staff_out,
    no_cov_staff_out = no_cov_staff_out,
    total_staff_out = total_staff_out,
    num_staff = num_staff,
    cov_prop_staff_out = (cov_staff_out / num_staff) *
      100,
    no_cov_prop_staff_out = (no_cov_staff_out / num_staff) *
      100,
    total_prop_staff_out = (total_staff_out / num_staff) *
      100
  )
  
  group_df <- rbind(group_out, group_df)
}


```

```{r, warnings =FALSE}

#2 week lag - people returning after 2 weeks

group_df_lag <- group_df %>%
  group_by(group, model) %>%
  mutate(
    nrows = n(),
    end_lag = nrows[1] - 14 ,
    cov_staff_return = ifelse(nrows > 14, c(rep(0, 14), cov_staff_out[1:end_lag]), 0))


###############Only getting returners from 14days after last data point
group_df_lag$cov_staff_return <- ifelse(group_df_lag$date < first_date + 14, 0 ,group_df_lag$cov_staff_return)
###############

group_df_lag$cov_lag_staff_out <- group_df_lag$cov_staff_out - group_df_lag$cov_staff_return

group_df_lag$cov_lag_prop <- (group_df_lag$cov_lag_staff_out / group_df_lag$num_staff) * 100

group_df_lag$total_staff_out <- group_df_lag$cov_lag_staff_out + group_df_lag$no_cov_staff_out

group_df_lag$total_prop_staff_out <- (group_df_lag$total_staff_out / group_df_lag$num_staff) * 100

group_df_lag <- group_df_lag %>% 
  select(
    date,
    group,
    model,
    cov_staff_out,
    cov_lag_staff_out,
    cov_staff_return,
    no_cov_staff_out,
    total_staff_out,
    cov_prop_staff_out,
    cov_lag_prop,
    no_cov_prop_staff_out,
    total_prop_staff_out
  )


```

Staff groups

```{r}
num_pl_df <- data.frame(group_df_lag %>% 
  select(date, group, model,total_staff_out, cov_lag_staff_out) %>% 
  pivot_longer(., cols = c("total_staff_out", "cov_lag_staff_out"))) %>% mutate(model = factor(model, levels = c("Nat75", "Dev50", "Dev2.5", "Dev97.5")))



```

All Staff

```{r}
all_staff<- data.frame(num_pl_df %>% 
              group_by(date, model, name) %>% 
              summarise(value = sum(value)) %>%               
              select(date, model,  name, value) %>% 
              ungroup())
```

Group Plot

```{r}

ymax <- ifelse(max(num_pl_df$value)> staff_num, staff_num, NA)

num_plot_cov <-
  ggplot(num_pl_df %>% 
           filter(date > as.Date("2020-03-19") & name == "cov_lag_staff_out"),
    aes(
      x = date,
      y = value,
      group = interaction(model, group)
    )
  ) +
  geom_line(aes(col = model, linetype = model, size = model)) +
  geom_point(data = num_pl_df %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "cov_lag_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  facet_wrap( ~ group) +
  ylab("Number Staff Absent") +
  xlab("Date") +
  theme(legend.title = element_blank()) +
  ggtitle(paste0("Staff Numbers Absent due to COVID-19 - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  theme_bw()+
   scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  ylim(0,ymax)
 
num_plot_cov

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_COVID_Absences_Numbers_Staff_Groups.png"), width = 30, height = 20, units = "cm")


```


```{r}

num_plot_all <-
  ggplot(num_pl_df %>% 
           filter(date > as.Date("2020-03-19") & name == "total_staff_out"),
    aes(
      x = date,
      y = value,
      group = interaction(model, group)
    )
  ) +
  geom_line(aes(col = model, linetype = model, size = model)) +
  geom_point(data = num_pl_df %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "total_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  facet_wrap( ~ group) +
  ylab("Number Staff Absent") +
  xlab("Date") +
  scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  ggtitle(paste0("Staff Numbers Absent (All) - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  theme_bw() +
  ylim(0,ymax)
 
num_plot_all

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_All_Absences_Numbers_Staff_Groups.png"), width = 30, height = 20, units = "cm")


```


All Staff Plot
```{r}

ymax <- ifelse(max(all_staff$value)> staff_num, staff_num, NA)


all_staff_plot_cov <- ggplot(all_staff %>% filter(date > as.Date("2020-03-19")& name == "cov_lag_staff_out"),aes(x = date, y = value, col = model, group = interaction(model,name)))+
  geom_line(aes(linetype = model, size = model)) +
  geom_point(data = all_staff %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "cov_lag_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  ylab("Number Staff Absent")+
  xlab("Date")+
  scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  ggtitle(paste0("Staff Numbers Absent due to COVID-19 - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  theme_bw() +
  ylim(0,ymax)


all_staff_plot_cov

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_COVID_Absences_Numbers_All_Staff.png"), width = 30, height = 20, units = "cm")

```


```{r}

all_staff_plot_total <- ggplot(all_staff %>% filter(date > as.Date("2020-03-19")& name == "total_staff_out"),aes(x = date, y = value, col = model, group = interaction(model,name)))+
  geom_line(aes(linetype = model, size = model)) +
  geom_point(data = all_staff %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "total_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  ylab("Number Staff Absent")+
  xlab("Date")+
  scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  ggtitle(paste0("Staff Numbers Absent (All) - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  theme_bw() +
  ylim(0,ymax)


all_staff_plot_total

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_All_Absences_Numbers_All_Staff.png"), width = 30, height = 20, units = "cm")

```



Proportion Plots
```{r}

prop_pl_df <- group_df_lag %>% 
  select(date, group, model,total_prop_staff_out, cov_lag_prop, no_cov_prop_staff_out) %>% 
  pivot_longer(., cols = c("total_prop_staff_out", "cov_lag_prop")) 

prop_pl_df$model <- factor(prop_pl_df$model, levels = c("Nat75", "Dev50", "Dev2.5", "Dev97.5"))

prop_plot_cov <- ggplot(prop_pl_df %>% filter(date > as.Date("2020-03-19") & name == "cov_lag_prop"),aes(x = date, y = value, col = model, group = interaction(model, group,name)))+
  geom_line(aes(col = model, linetype = model, size = model)) +
  geom_point(data = prop_pl_df %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "cov_lag_prop") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  facet_wrap(~group)+
  ylab("Proportion Staff Absent %")+
  xlab("Date")+
 scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  theme_bw()+
  ggtitle(paste0("Percentage Staff Absent due to COVID-19 - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  ylim(0,100)


prop_plot_cov

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_COVID_Absences_Proportions_Staff_Groups.png"), width = 30, height = 20, units = "cm")

```

```{r}

prop_plot_all <- ggplot(prop_pl_df %>% filter(date > as.Date("2020-03-19") & name == "total_prop_staff_out"),aes(x = date, y = value, col = model, group = interaction(model, group,name)))+
  geom_line(aes(col = model, linetype = model, size = model)) +
  geom_point(data = prop_pl_df %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "total_prop_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
  facet_wrap(~group)+
  ylab("Proportion Staff Absent %")+
  xlab("Date")+
 scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  theme_bw()+
  ggtitle(paste0("Percentage Staff Absent (All)- ", hosp))+
  labs(color = "", size = "", linetype= "")+
  ylim(0,100)


prop_plot_all

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_All_Absences_Proportions_Staff_Groups.png"), width = 30, height = 20, units = "cm")

```


All Staff Prop
```{r}
total_staff <- sum(Number_Staff_By_Group$Number_Staff[1:8])

all_staff$prop_value <- (all_staff$value /total_staff) *100


all_props_cov <- ggplot(all_staff %>% filter(date > as.Date("2020-03-19") & name == "cov_lag_staff_out"),aes(x = date, y = prop_value, col = model, group = interaction(model, name)))+
  geom_line(aes(linetype = model, size = model)) +
  geom_point(data = all_staff %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "cov_lag_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
   ylab("Proportion Staff Absent %")+
  xlab("Date")+
  scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  theme_bw()+
  ggtitle(paste0("Percentage Staff Absent - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  ylim(0,100)

all_props_cov

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_COVID_Absences_Proportions_All_Staff.png"), width = 30, height = 20, units = "cm")


```


```{r}
total_staff <- sum(Number_Staff_By_Group$Number_Staff[1:8])

all_staff$prop_value <- (all_staff$value /total_staff) *100


all_props_tot <- ggplot(all_staff %>% filter(date > as.Date("2020-03-19") & name == "total_staff_out"),aes(x = date, y = prop_value, col = model, group = interaction(model, name)))+
  geom_line(aes(linetype = model, size = model)) +
  geom_point(data = all_staff %>% filter(date > as.Date("2020-03-19") & date <= first_date & name == "total_staff_out") , col = "black") +
  geom_vline(xintercept = first_date, linetype = "dotted") +
   ylab("Proportion Staff Absent %")+
  xlab("Date")+
  scale_color_manual(values = c("#00BFC4",rep("#F8766D", 3))) +
  scale_linetype_manual(values = c("solid", "solid", "dotted", "dotted"))+
  scale_size_manual(values = c(1.5,1.5,1,1))+
  theme(legend.title = element_blank()) +
  theme_bw()+
  ggtitle(paste0("Percentage Staff Absent - ", hosp))+
  labs(color = "", size = "", linetype= "")+
  ylim(0,100)

all_props_tot

ggsave(paste0(out_dir,hosp, "_",format(Sys.Date(), "%Y%m%d"),"_All_Absences_Proportions_All_Staff.png"), width = 30, height = 20, units = "cm")


```
